### ISSUE TITLE
Explanation of spec failure (bad equality)

### ISSUE THREAD

**Issue by jshthornton** [nicolas-van/ring.js#14]
I have the following example:
```
var A = ring.create({

});

var C = {};

var B = ring.create({
	item: A,
	item2: C
});

var b = new B();

expect(b.item).toEqual(A);
expect(b.item2).toEqual(C);
```

Test 1 fails, test 2 succeeds.
The second needs to succeed due to this example closely resembling Backbone Model / Collection relationships.

It appears to be morphing the function somehow:

**Before**
```
function Instance() {
    this.$super = null;
    this.__ringConstructor__.apply(this, arguments);
}
```

**After**
```
function r(){return(this instanceof r?e:n).apply(t,arguments)}
```

**Comment by nicolas-van** [comment]
Couldn't reproduce In 2.0.2 with the following code:

    var A = ring.create({

    });

    var C = {};

    var B = ring.create({
        item: A,
        item2: C
    });

    var b = new B();

    console.log(b.item == A); // prints true
    console.log(b.item === A); // prints true

If you reopen, please observe the following advises:

* You should indicate the concerned version of ring.js.
* You should avoid using external libraries in your example. If you do please explain which library is used.
* You should explain in which browsers you tested (testing in multiple browsers is preferable if you can).

Anyway, thanks for reporting.
