### ISSUE TITLE
Weird Constructor Name

### ISSUE THREAD

**Issue by rain1024** [nicolas-van/ring.js#15]
In section `Constructor` at documentation page, you described

> When the dictionary of properties given to ring.create() contains a method named constructor, that method will be called during the object construction with the argument

But it's not working at all

```
var A = ring.create({
    constructor: function(name) {
        this.name = name;
    },
});
var a = new A("Nicolas");
console.log(a.name); //  <- print "undefined"
```

However if I change `constructor` to `init`

```
var A = ring.create({
    init: function(name) { // change constructor to init
        this.name = name;
    },
});
var a = new A("Nicolas");
console.log(a.name); // print "Nicolas" <- it works well
```

How can it happend? Does document wrong?

**Comment by nicolas-van** [comment]
That's the behavior of the 1.0 version. The documentation speaks about the behavior of the 2.0 version.
