### ISSUE TITLE
Recommended to increase the storage constructor parameters

### ISSUE THREAD

**Issue by zhouxianjun** [nicolas-van/ring.js#17]
changed：

var claz = function Instance() {
            this.$super = null;
            this.args = arguments; //save constructor parameters
            this.**ringConstructor**.apply(this, arguments);
        };

**Comment by nicolas-van** [comment]
Hello.

Why do you want to do that? It's easily doable in child classes if you need to and imposing that behavior in all classes could lead to memory leaks.

**Comment by zhouxianjun** [comment]
Hello nicolas-van
For example: re - instance the current object
var A = ring.create({
    constructor: function(name){
        this.name = name;
    }
});
var tmpA = new A('Gary');
var tmp = tmpA; // or clone
tmpA.test = 'changed';
console.log(tmp.test); //print changed

var tmp = new tmpA.constructor(tmpA.args.callee);
console.log(tmp.test); //print undefined

**Comment by nicolas-van** [comment]
You know when I asked you that question I expected a rationale in English, not a bunch of code that's maybe kind of implying something.
